const Data = {
    "Breakfast": 
        [
            {
              "id": "1",
              "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1jirm4qyJkDxpToXcpnQYs3e8tTD9Uj0SGw&usqp=CAU",
              "name": "Khaman",
              "category": "Breakfast",
              "price": "80",
              "description": "Khaman is a popular Gujarati snack made from steamed and seasoned gram flour."
            },
            {
              "id": "2",
              "image": "https://www.dineout.co.in/blog/wp-content/uploads/2018/01/Gujrati-Food-Blog-Banner.jpg",
              "name": "Khandvi",
              "category": "Breakfast",
              "price": "60",
              "description": "A flavorful Gujarati soft, silky rolls made from a chickpea flour batter and tempered with mustard and sesame seeds.",
            },
            {
              "id": "3",
              "image": "https://media.istockphoto.com/id/516105760/photo/methi-paratha.jpg?s=612x612&w=0&k=20&c=Jm-xSkbJ2w_D8wDQZf6Dsrr9T5aPldoBnW-PiSEriAQ=",
              "name": "Thepla",
              "category": "Breakfast",
              "price": "50",
              "description": "A popular and easy-to-make Gujarati breakfast dish, a spiced flatbread made with wheat flour, fenugreek leaves.",
            },
            {
              "id": "4",
              "image": "https://insanelygoodrecipes.com/wp-content/uploads/2021/03/Homemade-Grilled-Cheese-Sandwich-with-Tomatoes.png",
              "name": "Sandwich",
              "category": "Breakfast",
              "price": "40",
              "description": "A classic sandwich made with fresh bread, lettuce, tomato, and your choice of cheese or vegetables.",
            },
            {
                "id":"5",
                "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcyogLYhBdSwctdu-8hvQWOBBnAF2qrYXO-Q&usqp=CAU",
                "name": "Samosa",
                "category": "Breakfast",
                "price": "50" ,
                "description": "A popular Indian snack made with a crispy pastry shell filled with spiced potatoes and peas.",
            },
            {
                "id":"6",
                "image": "https://ktgrestaurant.com/admin/upload/48556mydelicious-recipes-masala-dosa-with-batter_11zon.webp",
                "name": "Dosa",
                "category": "Breakfast",
                "price": "120" ,
                "description": "A thin and crispy crepe made from fermented rice and lentil batter, often served with coconut chutney and sambar..",
            },
            {
                "id":"7",
                "image": "https://mishry.com/wp-content/uploads/2019/12/breakfast-2408818_1280.jpg",
                "name": "Idli",
                "category": "Breakfast",
                "price": "60" ,
                "description": "A South Indian breakfast dish made with a fermented batter of rice and lentils, steamed and served with chutney and sambar.",
            },
            {
                "id":"8",
                "image": "https://rumkisgoldenspoon.com/wp-content/uploads/2021/11/Dabeli-recipe.jpg",
                "name": "Dabeli",
                "category": "Breakfast",
                "price": "30" ,
                "description": "A popular street food snack made from a sweet and spicy potato filling served inside a bread bun, topped with peanuts and chutney.",
            },
            {
                "id":"9",
                "image": "https://www.archanaskitchen.com/images/archanaskitchen/Indian_Breakfast_Tiffins/Indian_Aloo_Batata_Poha_with_Pomegranates_Recipe_Archanas_Kitchen-1_400.jpg",
                "name": "Batata Pau",
                "category": "Breakfast",
                "price": "30" ,
                "description": "A popular Gujarati street food that consists of a spicy potato, served hot with chutney and fried green chillies.",
            },
            {
                "id":"10",
                "image": "https://static.toiimg.com/photo/msid-80362218/80362218.jpg",
                "name": "Gujarati Thali",
                "category": "Lunch",
                "price": "150" ,
                "description": "A Gujarati Thali consists of a variety of vegetarian dishes including curries, bread, rice, lentils, and desserts,small portions on a single plate.",
            },
            {
              "id":"11",
              "image": "https://maakhanbhog.com/media/catalog/product/cache/b16015e376afa54972761b421b93f3f0/s/p/special-punjabi-thali.jpg",
              "name": "Punjabi Thali",
              "category": "Lunch",
              "price": "180" ,
              "description": "A Punjabi Thali includes various Punjabi delicacies such as butter chicken, sarson ka saag, chana masala, dal makhani, naan, lassi on a single plate.",
          },
          {
            "id":"12",
            "image": "https://www.inditales.com/wp-content/uploads/2019/05/maharashtra-thali.jpg",
            "name": "Maharastra Thali",
            "category": "Lunch",
            "price": "170" ,
            "description": " Maharashtrian Thali are available Sabudana Wada,Varan Bhat, Chana Daal,Puran Poli ,Shrikhand on a single plate.",
        },
        {
          "id":"13",
          "image": "https://www.inditales.com/wp-content/uploads/2019/05/rajasthani-thali.jpg",
          "name": "Rajasthani Thali",
          "category": "Lunch",
          "price": "140" ,
          "description": "A Rajasthani Thali includes dishes such as dal baati churma, gatte ki sabzi, ker sangri, papad, and a range of sweets and desserts on a single plate.",
      },
      {
        "id":"14",
        "image": "https://www.madhuseverydayindian.com/wp-content/uploads/2022/11/easy-vegetable-biryani.jpg",
        "name": "Vegetable Biryani",
        "category": "Lunch",
        "price": "100" ,
        "description": "Vegetable biryani is a classic Indian rice dish that spiced rice layered with mixed vegetables, herbs, and spices, resulting in a flavorful and filling meal.",
    },
    {
      "id":"15",
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPkgnPq1bCuuMzjZUQXvfjNqybb8oojKitoA&usqp=CAU",
      "name": "Paneer Curry",
      "category": "Dinner",
      "price": "90" ,
      "description": "Paneer curry is a flavorful North Indian dish made with paneer cheese in a rich and aromatic tomato-based sauce.",
  },
  {
    "id":"16",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGR3oGgYIB_pvuiMfQedxQKePLEXskyia4cBSyd63jf7vReM76o4J2gd8Cthu2eZEDoWw&usqp=CAU",
    "name": "Palak Paneer",
    "category": "Dinner",
    "price": "80" ,
    "description": "A Palak paneer is a vegetarian Indian dish made of creamy spinach and paneer cheese.",
},
{
  "id":"17",
  "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQABap79f1ku2LnY1pK6ljJ1Sv9ex55sXpqug&usqp=CAU",
  "name": "Rajma Chaval",
  "category": "Dinner",
  "price": "120" ,
  "description": "A Rajma chaval is a classic Punjabi dish featuring kidney beans in a spiced tomato gravy.",
},
    ]
}
export {Data};